apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: podinfo
  namespace: flux-system
spec:
  interval: 30m0s
  path: clusters/openshift-cluster/flux-system/base  # Update this path
  prune: true
  retryInterval: 1m0s
  sourceRef:
    kind: GitRepository
    name: podinfo
  secretRef:
    name: flux-system
  targetNamespace: default
  timeout: 3m0s
  wait: true

