name: Deploy to OpenShift

on:
  push:
    branches:
      - main  # Trigger deployment on push to the main branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository code
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up kubeconfig with the public IP of the OpenShift API server
      - name: Set up kubeconfig
        run: |
          mkdir -p ~/.kube
          echo "apiVersion: v1
          kind: Config
          clusters:
          - cluster:
              server: https://3.110.220.235:6443
              insecure-skip-tls-verify: true
            name: openshift
          contexts:
          - context:
              cluster: openshift
              user: admin
            name: default
          users:
          - name: admin
            user:
              token: ${{ secrets.KUBE_TOKEN }}" > ~/.kube/config
          chmod 600 ~/.kube/config

      # Debug: Output kubeconfig file for verification
      - name: Debug kubeconfig
        run: |
          cat ~/.kube/config

      # Install OpenShift CLI
      - name: Install OpenShift CLI
        run: |
          curl -L https://mirror.openshift.com/pub/openshift-v4/clients/oc/latest/linux/oc.tar.gz | tar -xz
          sudo mv oc /usr/local/bin/oc
          oc version

      # Verify that we are logged into the OpenShift cluster
      - name: Verify OpenShift context
        run: |
          oc whoami
          oc get nodes

      # Apply Kubernetes manifests using oc
      - name: Apply OpenShift manifests
        run: |
          oc apply -f clusters/openshift-cluster/flux-system/base
