name: Deploy to OpenShift

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up SSH tunnel to Kubernetes API
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Forward Kubernetes API through SSH tunnel
        run: |
          ssh -N -L 6443:localhost:6443 ${{ secrets.EC2_HOST }} &
          sleep 10

      - name: Install OpenShift CLI
        run: |
          curl -L https://mirror.openshift.com/pub/openshift-v4/clients/oc/latest/linux/oc.tar.gz | tar -xz
          sudo mv oc /usr/local/bin/
          oc version

      - name: Verify Kubernetes context
        run: |
          kubectl config set-cluster kubernetes --server=https://localhost:6443 --insecure-skip-tls-verify=true
          kubectl get nodes
          
      - name: Apply Kubernetes manifests
        run: |
          kubectl apply -f clusters/openshift-cluster/flux-system/base
